name = "geostamp-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
JWT_SECRET = "geostamp-production-secret-key-2024"

[[kv_namespaces]]
binding = "GEOSTAMP_KV"
id = "a1a972347f2e4283815750de6134c0f5"

[env.production]
name = "geostamp-api"
routes = [
  { pattern = "api.geostamp.top/*", zone_name = "geostamp.top" }
]

[env.production.vars]
JWT_SECRET = "geostamp-production-secret-key-2024"
# CREEM_API_KEY is set via `wrangler secret put` (do NOT put plaintext here)
# RESEND_API_KEY is set via `wrangler secret put` (do NOT put plaintext here)

[[env.production.kv_namespaces]]
binding = "GEOSTAMP_KV"
id = "a1a972347f2e4283815750de6134c0f5"
